Update admixtools to 7.0.1
bioconda/bioconda-recipes pull request #24213
Opened 2020-09-03 08:11 UTC by BiocondaBot

Update [`admixtools`](https://bioconda.github.io/recipes/admixtools/README.html): **6.0** &rarr; **7.0.1**

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat)](http://bioconda.github.io/recipes/admixtools/README.html) [![Conda](https://img.shields.io/conda/dn/bioconda/admixtools.svg)](https://anaconda.org/bioconda/admixtools/files)

Info | Link
-----|-----
Recipe | [`recipes/admixtools`](https://github.com//bioconda/bioconda-recipes/tree/bump/admixtools/recipes/admixtools) (click to view/edit other files)
Releases |[https://github.com/DReichLab/AdmixTools/tags](https://github.com/DReichLab/AdmixTools/tags)
Author | `@DReichLab`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

2020-09-05 12:56 UTC, bwlang approved these changes

2020-09-05 13:02 UTC, bwlang commented
looks like this update is missing some build requirements...
```
08:21:17 BIOCONDA INFO (OUT) cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/admixtools-7.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -c -g -p -Wimplicit -I./ -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include  -c -o strsubs.o strsubs.c
08:21:17 BIOCONDA INFO (OUT) make[1]: cc: Command not found
```

2020-09-05 13:06 UTC, bwlang requested changes
did not mean to approve this yet... looks like this will need some build updates to work.

2020-12-07 15:59 UTC, rpetit3 approved these changes

2020-12-07 16:00 UTC, rpetit3 commented
@bioconda-bot please merge

2020-12-07 16:02 UTC, rpetit3 commented
@bioconda-bot please fetch artifacts

2020-12-07 16:04 UTC, rpetit3 approved these changes

2020-12-07 16:05 UTC, rpetit3 commented
@bwlang Looks like you need to approve the changes to push this forward.

2020-12-18 13:17 UTC, rpetit3 commented
Pinging @bwlang again

2020-12-18 17:21 UTC, bwlang approved these changes

2020-12-18 17:21 UTC, bwlang commented on recipes/admixtools/makefile-compiler.patch
> +From: "Robert A. Petit III" <robbie.petit@gmail.com>
Are you sure you want this detail in here?

2020-12-18 17:22 UTC, bwlang commented
> Pinging @bwlang again

Thanks for the reminder... not sure this needed me specifically - just some warm body (brain???)

2020-12-18 17:33 UTC, rpetit3 commented
Thanks @bwlang ! Haha yeah it needed your approval since you requested a change back in September.

2020-12-18 17:33 UTC, rpetit3 commented
@BiocondaBot please merge

2020-12-18 17:44 UTC, merged