Add CONSENT a self long read corrector v2.1
bioconda/bioconda-recipes pull request #24247
Opened 2020-09-04 16:53 UTC by natir

Add CONSENT a self corrector long-reads.
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2020-09-05 10:06 UTC, natir commented
@BiocondaBot please update

2020-09-08 18:19 UTC, natir commented
@BiocondaBot please update

2020-09-08 19:07 UTC, natir commented
Hello everyone,

Ok for this package I made many bad hack, we can probably found a better way, to solve all issues.

Create a package for dependencies could be a good solution but I'm pretty sure dependencies of this package isn't useful for other people and I prefer not to use my time to create these packages.

My main question is why the build failed on docker image build?

2020-09-14 11:19 UTC, natir commented
@BiocondaBot please update

2020-09-14 12:06 UTC, natir commented
@BiocondaBot please fetch artifacts

2020-09-14 12:17 UTC, natir commented
@BiocondaBot please add label

2020-09-14 16:20 UTC, innovate-invent requested changes

2020-09-15 13:22 UTC, natir commented on recipes/consent/build.sh
> +fi
env variable $PKG_NAME, $PKG_VERSION, $PKG_BUILDNUM can be interpeted durring patch step ?

2020-09-15 13:25 UTC, natir commented on recipes/consent/build.sh
> +cd ..
I try to simplify the cmake part but we can maybe found a better way

2020-09-15 13:25 UTC, natir commented on recipes/consent/build.sh
> +cd ..
done

2020-09-15 16:58 UTC, innovate-invent commented on recipes/consent/build.sh
> +fi
I see, that is unfortunate.

2020-09-15 17:08 UTC, innovate-invent commented on recipes/consent/build.sh
> +cd ..
I am not sure about cmake. Perhaps the following:
```
cmake -DCMAKE_BUILD_TYPE=Release BMEAN/spoa
make -C BMEAN/spoa/build
```

2020-09-15 17:22 UTC, natir commented on recipes/consent/build.sh
> +cd ..
It needs another option but I found it

2020-09-15 17:39 UTC, innovate-invent approved these changes
Looks great, thanks for the contribution!

2020-09-15 17:40 UTC, natir commented
@BiocondaBot please merge

2020-09-15 17:46 UTC, merged