Update r-pipette to 0.4.21
bioconda/bioconda-recipes pull request #25757
Opened 2020-12-10 17:10 UTC by BiocondaBot

Update [`r-pipette`](https://bioconda.github.io/recipes/r-pipette/README.html): **0.4.20** &rarr; **0.4.21**

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat)](http://bioconda.github.io/recipes/r-pipette/README.html) [![Conda](https://img.shields.io/conda/dn/bioconda/r-pipette.svg)](https://anaconda.org/bioconda/r-pipette/files)

Info | Link
-----|-----
Recipe | [`recipes/r-pipette`](https://github.com//bioconda/bioconda-recipes/tree/bump/r_pipette/recipes/r-pipette) (click to view/edit other files)
Releases |[https://github.com/acidgenomics/pipette/tags](https://github.com/acidgenomics/pipette/tags)
Recipe Maintainer(s) | @mjsteinbaugh
Author | `@acidgenomics`
***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

2020-12-10 17:22 UTC, mjsteinbaugh requested changes
Needs a couple of manual updates to recipe

2020-12-10 22:04 UTC, mjsteinbaugh commented
Recipe needs update to `r-acidbase` dependency, then good to go

2020-12-17 13:29 UTC, apeltzer approved these changes

2020-12-17 13:29 UTC, apeltzer commented
@bioconda-bot please merge

2020-12-18 17:27 UTC, mjsteinbaugh approved these changes

2020-12-18 17:27 UTC, merged