Initial commit of PegasusIO
bioconda/bioconda-recipes pull request #25845
Opened 2020-12-17 07:20 UTC by yihming

This is a package manipulating multi-modal omics data, with auxiliary functionality on count matrix aggregation and quality-control. And it's also the IO module of Pegasus, a single-cell data analysis package in Python.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2020-12-17 19:28 UTC, yihming commented
@BiocondaBot please add label

2020-12-18 07:36 UTC, dpryan79 requested changes
See comments. BTW, we can't edit your PR (perhaps your organization prevents that), otherwise I'd have just directly made the suggested changes.

2020-12-18 07:36 UTC, dpryan79 commented on recipes/pegasusio/meta.yaml
> +    entry_points:
Please put the following line in the `build:` section:

    skip: True  # [py27]

2020-12-18 07:36 UTC, dpryan79 commented on recipes/pegasusio/meta.yaml
> +        - python >=3.6
Please remove `>=3.6`

2020-12-18 07:36 UTC, dpryan79 commented on recipes/pegasusio/meta.yaml
> +        - numpy
It's implied that you need python, but please make that explicit by adding ` - python` to the run: section.

2020-12-18 08:23 UTC, yihming commented
@dpryan79 Thank you so much for your suggestions! I've updated my recipe.

BTW, may I ask the meaning of `skip: True  # [py27]`? In specific, would "# [py27]" be parsed so that the build only skip Python 2? Thanks!

2020-12-18 09:08 UTC, dpryan79 commented
Yes, `skip: True  # [py27]` means exactly that python 2.7 builds will be skipped. Since this requires compiling against specific versions of python, we can't restrict the python version in the host or run section (doing so results in a build for only python 3.8).

2020-12-18 09:15 UTC, dpryan79 commented
@bioconda-bot please fetch artifacts

2020-12-18 09:17 UTC, dpryan79 approved these changes

2020-12-18 09:17 UTC, dpryan79 commented
@bioconda-bot please merge

2020-12-18 09:28 UTC, merged