Add mapula recipe
bioconda/bioconda-recipes pull request #26913
Opened 2021-02-19 21:21 UTC by Karhide

Add mapula

2021-02-19 21:26 UTC, cjw85 approved these changes

2021-02-19 21:28 UTC, cjw85 requested changes
Only python as pip need to be listed in the host requirements

2021-02-19 21:29 UTC, cjw85 approved these changes

2021-02-19 21:34 UTC, cjw85 approved these changes

2021-02-21 21:06 UTC, bgruening commented
@bioconda-bot please merge

2021-02-21 21:23 UTC, merged