Add Cartools v1.1.3
bioconda/bioconda-recipes pull request #28429
Opened 2021-05-11 10:07 UTC by Smeds

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2021-05-11 19:38 UTC, fanninpm commented on recipes/cartools/meta.yaml
> +
> `ERROR: recipes/cartools/meta.yaml:0: missing_tests: The recipe is missing tests.`
```suggestion

test:
  commands:
    - python CARTools.py --help

```

2021-05-31 07:02 UTC, Smeds commented on recipes/cartools/meta.yaml
> +
done

2021-05-31 07:02 UTC, Smeds commented on recipes/cartools/meta.yaml
> +    - python
done

2021-05-31 07:02 UTC, Smeds commented on recipes/cartools/meta.yaml
> +  sha256: eb9e939ae2819cb9020ac4a8c2ea7d3e983356f36d1b0bf4d2c02a3405d33f7f
done

2021-05-31 07:04 UTC, Smeds commented
Any more updates needed?

2021-05-31 19:05 UTC, fanninpm commented
@BiocondaBot please update

2021-05-31 19:10 UTC, fanninpm commented
> Any more updates needed?

Are you satisfied with the artifacts?

2021-06-03 18:21 UTC, fanninpm commented
@BiocondaBot please add label

2021-06-03 18:30 UTC, dpryan79 requested changes
One minor tweak needed

2021-06-03 18:30 UTC, dpryan79 commented on recipes/cartools/meta.yaml
> +  noarch: generic
Please change this to `noarch: python` so conda knows to move things around during deployment.

2022-06-28 14:38 UTC, corneliusroemer commented
CI fails, so can't be merged

2022-09-11 09:02 UTC, dpryan79 approved these changes

2022-09-11 09:03 UTC, dpryan79 commented
@BiocondaBot please fetch artifacts

2022-09-11 09:13 UTC, merged