Add scBio R package
bioconda/bioconda-recipes pull request #30609
Opened 2021-09-21 08:30 UTC by PelzKo

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2021-09-21 08:37 UTC, grst requested changes

2021-09-21 08:37 UTC, grst commented on recipes/r-scbio/meta.yaml
> +    - https://github.com/amitfrish/scBio/releases/download/{{ version }}/scBio_{{ version }}.tar.gz
This URL is probably more stable as it is automatically generated by github: 
```
https://github.com/amitfrish/scBio/archive/refs/tags/{{ version }}.tar.gz
```

The other archive is manually generated and uploaded by the author.

2021-09-21 08:37 UTC, grst commented on recipes/r-scbio/meta.yaml
> +  number: 4
build number should be 0 initially

2021-09-21 08:37 UTC, grst commented on recipes/r-scbio/meta.yaml
> +  license_family: other
license family should be `GPL` to be in agreement with `license`

2021-09-21 09:46 UTC, PelzKo commented
@BiocondaBot please add label

2021-09-21 09:47 UTC, grst approved these changes

2021-09-23 11:34 UTC, druvus commented
@BiocondaBot please merge

2021-09-23 11:35 UTC, merged