Add autogenes Python package
bioconda/bioconda-recipes pull request #30614
Opened 2021-09-21 12:45 UTC by PelzKo

Added the AutoGeneS Python package

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2021-09-21 13:03 UTC, grst requested changes

2021-09-21 13:03 UTC, grst commented on recipes/autogenes/meta.yaml
> +    - matplotlib >=3.0
`noarch: python` packages don't require all dependencies under `host`. It's usually just `python` and `pip`. 

If a package has some `C` dependencies, you would additionally require a compiler. 

Explanation: `host` are the packages needed to *build/install* the package, `run` are the dependencies required to *run/execute* the package.

2021-09-21 13:03 UTC, grst commented on recipes/autogenes/meta.yaml
> +  noarch: generic
should be `noarch: python`

2021-09-21 13:58 UTC, grst commented on recipes/autogenes/meta.yaml
> +    - https://files.pythonhosted.org/packages/f0/04/4768c40962c38dd15b6cbd67d23f1c0d97d2dedeaa6558f6f8689458b4c5/autogenes-{{ version }}.tar.gz
I think this URL won't work once the version gets bumped... 
It usually looks more like this `https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz`

2021-09-22 13:15 UTC, grst commented on recipes/autogenes/meta.yaml
> +    - http://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
```suggestion
    - https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
```

2021-09-22 13:37 UTC, PelzKo commented
@BiocondaBot please add label

2021-09-22 13:45 UTC, grst approved these changes
LGTM!

2021-09-23 11:34 UTC, druvus commented
@BiocondaBot please merge

2021-09-23 11:35 UTC, merged