Update regenie recipe
bioconda/bioconda-recipes pull request #33778
Opened 2022-03-18 10:33 UTC by joellembatchou

Describe your pull request here

Update to make regenie recipe for latest v3.0.1
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2022-03-18 10:52 UTC, joellembatchou commented
@BiocondaBot please add label

2022-03-18 10:56 UTC, matuskosut commented
@BiocondaBot please fetch artifacts

2022-03-18 11:04 UTC, matuskosut commented
It seems that this file is missing:
```
patches/0005-use-conda-cmakelist-file.patch
```

2022-03-18 11:05 UTC, dpryan79 submitted a review, later dismissed

2022-03-18 11:10 UTC, joellembatchou commented
I checked the test_linux log and it says "Ignoring 1 blacklisted recipes (regenie)". I added the patch file though

2022-03-18 11:17 UTC, dpryan79 commented
I've removed this from the blacklist. I think I ran into issues during the last migration with some dependencies conflicting.

2022-03-18 22:27 UTC, joellembatchou commented
@BiocondaBot please add label

2022-03-18 23:30 UTC, joellembatchou commented
@matuskosut Finished passing all the edits and it looks like it passed all the checks. Let me know if I need to do anything further.

2022-03-18 23:32 UTC, dpryan79 requested changes
A couple small changes and this should be good to go

2022-03-18 23:32 UTC, dpryan79 commented on recipes/regenie/conda_build_config.yaml
>    - 1.74
Can you remove this file? boost_cpp is pinned to 1.74 project-wide already.

2022-03-18 23:32 UTC, dpryan79 commented on recipes/regenie/meta.yaml
> +    - boost-cpp {{ boost_cpp }}
You can remove "{{ boost_cpp}}" both here and below. boost-cpp is always pinned to the exact patch version a package was built with.

2022-03-20 09:27 UTC, matuskosut commented
@BiocondaBot please fetch artifacts

2022-03-20 10:04 UTC, matuskosut approved these changes
LGTM

2022-03-20 10:05 UTC, matuskosut commented
@BiocondaBot please merge

2022-03-20 13:33 UTC, dpryan79 approved these changes

2022-03-20 13:33 UTC, dpryan79 commented
@BiocondaBot please merge

2022-03-20 13:35 UTC, merged