Add recipe for Physlr
bioconda/bioconda-recipes pull request #34330
Opened 2022-04-14 22:06 UTC by afshinfard

Adding Physlr to bioconda

Physlr: construct a physical map using linked reads
GitHub: https://github.com/bcgsc/physlr

----

* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2022-06-22 22:44 UTC, sjackman requested changes

2022-06-22 22:44 UTC, sjackman commented on recipes/physlr/build.sh
> +cd ..
```suggestion
make -C src install
```

2022-06-22 22:44 UTC, sjackman commented on recipes/physlr/build.sh
> +mkdir -p ${PREFIX}/bin/
```suggestion
```
Redundant with the following lines.

2022-06-22 22:44 UTC, sjackman commented on recipes/physlr/build.sh
> +mkdir -p ${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/physlr
```suggestion
```
Delete and see below

2022-06-22 22:44 UTC, sjackman commented on recipes/physlr/build.sh
> +cp physlr/* ${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/physlr/
```suggestion
cp -a bin ${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/
cp -a physlr ${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/
```

2022-06-22 22:44 UTC, sjackman commented on recipes/physlr/build.sh
> +cp src/physlr-split-minimizers ${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/src/physlr-split-minimizers
```suggestion
cp src/physlr-indexlr src/physlr-makebf src/physlr-filter-bxmx src/physlr-filter-barcodes src/physlr-overlap src/physlr-split-minimizers ${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/src/
```
There appears to be unintentional copy-and-paste errors renaming files, like for example renaming `physlr-filter-bxmx` to `physlr-indexlr`.

2022-06-22 22:44 UTC, sjackman commented on recipes/physlr/build.sh
> +echo "make -f $(command -v ${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/bin/physlr-make) \$@" >> ${PREFIX}/bin/physlr
```suggestion
printf '#!/bin/bash\nexec make -f $(command -v '"${PREFIX}/bin/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/bin/physlr-make"') "$@" >${PREFIX}/bin/physlr
```

2022-06-22 22:44 UTC, sjackman commented on recipes/physlr/meta.yaml
> +    # - physlr test
Either uncomment or delete these comments.

2022-06-23 00:54 UTC, aafshinfard commented
Thanks for the corrections @sjackman; done; tests passing.

2022-06-23 17:58 UTC, sjackman commented on recipes/physlr/build.sh
> +#!/bin/bash
```suggestion
#!/bin/bash
set -eu
```
Fail on error or undefined variable.

2022-06-26 05:49 UTC, aafshinfard commented
Local build with `bioconda-utils` worked alright.
Local build with `conda-build` was successful.
Local install with `conda install --use-local` was also successful, and I was able to run `physlr` afterward:
```
$ physlr version
physlr 1.0.2

2022-06-28 18:17 UTC, aafshinfard commented
Awch, I found some issues I could not see as I had them already in my path. Will update shortly.

2022-06-30 22:35 UTC, aafshinfard commented
@BiocondaBot please fetch artifacts

2022-07-05 03:24 UTC, aafshinfard commented
@BiocondaBot please fetch artifacts

2022-07-05 04:21 UTC, aafshinfard commented
@BiocondaBot please fetch artifacts

2022-07-07 18:37 UTC, aafshinfard commented
@sjackman Made a new conda env and tested it on real human data and it worked alright

2022-07-10 19:11 UTC, sjackman approved these changes
LGTM

2022-07-11 21:40 UTC, aafshinfard commented
@bioconda/core ready to be merged, please

2022-07-12 02:06 UTC, daler commented
@BiocondaBot please merge

(thanks @aafshinfard @sjackman)

2022-07-12 02:07 UTC, merged