add sage recipes
bioconda/bioconda-recipes pull request #37807
Opened 2022-11-04 07:38 UTC by lcion-02

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2022-11-07 15:47 UTC, jpfeuffer requested changes
Thanks for the contribution. Some initial changes are required. After that, we need to check the actual build steps and see if cargo is actually necessary for running (I am no Rust expert but I doubt it).

2022-11-07 15:47 UTC, jpfeuffer commented on recipes/sage/build.sh
> +fi
This should be removed before merging. You can keep it for local testing until then.

2022-11-07 15:47 UTC, jpfeuffer commented on recipes/sage/meta.yaml
> +  version: {"0.7.1"}
```suggestion
{% set name = "sage" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower  }}
  version: {{ version  }}
```

2022-11-07 15:47 UTC, jpfeuffer commented on recipes/sage/meta.yaml
> +  url: https://github.com/lazear/sage/archive/refs/heads/master.zip
```suggestion
  url: https://github.com/lazear/sage/archive/refs/tags/v{{ version }}.tar.gz
```

2022-11-07 15:47 UTC, jpfeuffer commented on recipes/sage/meta.yaml
> +  version: {"0.7.1"}
Also add an
`sha: `
field. You can compute it after downloading the tar file with `sha1sum` for example.

2022-11-07 15:47 UTC, jpfeuffer commented on recipes/sage/meta.yaml
> +    script: cargo build --release
```suggestion
```

2022-11-07 15:47 UTC, jpfeuffer commented on recipes/sage/meta.yaml
> +  number: 1
```suggestion
  number: 1
  script: cargo build --release
```

2022-11-07 19:07 UTC, lazear commented
> Thanks for the contribution. Some initial changes are required. After that, we need to check the actual build steps and see if cargo is actually necessary for running (I am no Rust expert but I doubt it).

Cargo is definitely not necessary!

2022-11-08 06:03 UTC, ypriverol commented
@lcion-02 @lazear @jpfeuffer the following package: https://anaconda.org/conda-forge/sage is called sage and I think create conflicts with the name of our recipe. What other name we can put to the tool package? @lazear 

- ms-sage?

2022-11-08 06:09 UTC, lazear commented
> @lcion-02 @lazear @jpfeuffer the following package: https://anaconda.org/conda-forge/sage is called sage and I think create conflicts with the name of our recipe. What other name we can put to the tool package? @lazear
> 
>     * ms-sage?

@ypriverol  How about "sage-proteomics"? "sage-search"? No strong preference from me, really!

2022-11-08 06:10 UTC, ypriverol commented
I like sage-proteomics.

2022-11-08 06:12 UTC, ypriverol commented
@lcion-02 can you change the name of the package to sage-proteomics. Remember to change also the name of the folder.

2022-11-08 06:13 UTC, lcion-02 commented
> @lcion-02 can you change the name of the package to sage-proteomics. Remember to change also the name of the folder.

okay

2022-11-08 06:25 UTC, closed without merging