Update cellprofiler-core to 4.2.5
bioconda/bioconda-recipes pull request #38399
Opened 2022-12-14 19:09 UTC by BiocondaBot

Update [`cellprofiler-core`](https://bioconda.github.io/recipes/cellprofiler-core/README.html): **4.2.4** &rarr; **4.2.5**

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat)](http://bioconda.github.io/recipes/cellprofiler-core/README.html) [![Conda](https://img.shields.io/conda/dn/bioconda/cellprofiler-core.svg)](https://anaconda.org/bioconda/cellprofiler-core/files)

Info | Link or Description
-----|--------------------
Recipe | [`recipes/cellprofiler-core`](https://github.com//bioconda/bioconda-recipes/tree/bump/cellprofiler_core/recipes/cellprofiler-core) (click to view/edit other files)
Summary | Dependency for CellProfiler v4
Home | [https://github.com/CellProfiler/core](https://github.com/CellProfiler/core)
Releases |[https://pypi.org/pypi/cellprofiler-core/json](https://pypi.org/pypi/cellprofiler-core/json)
Recipe Maintainer(s) | @raivivek

***

This pull request was automatically generated (see [docs](https://bioconda.github.io/contributor/updating.html)).

2022-12-23 05:46 UTC, priesgo requested changes
See comment on dependencies

2022-12-23 05:46 UTC, priesgo commented on recipes/cellprofiler-core/meta.yaml
> +    - h5py >3.6.0
The right translation of `~=3.6.0` is `>=3.6.0,<3.7.0`. Same applies for other dependencies

2023-01-02 14:16 UTC, priesgo commented
ping @raivivek

2023-01-17 00:50 UTC, raivivek commented
@priesgo Would you be interesting in adding a commit to this PR addressing your requested change?

2023-01-17 07:10 UTC, closed without merging

2023-01-17 07:14 UTC, priesgo commented
Uh, what happened there?