Use sqlalchemy <2 in biophi
bioconda/bioconda-recipes pull request #39158
Opened 2023-02-03 08:02 UTC by prihoda

Use sqlalchemy <2 in biophi, increase build number

2023-02-03 11:51 UTC, prihoda commented
@BiocondaBot please add label

2023-02-03 12:54 UTC, johanneskoester requested changes

2023-02-03 12:54 UTC, johanneskoester commented on recipes/biophi/meta.yaml
> +    - sqlalchemy <2
Please add a comment with a reason here. The more info there is in the recipe, the better this can be maintained in the future.

2023-02-07 10:16 UTC, dpryan79 commented
@BiocondaBot please fetch artifacts

2023-02-07 10:47 UTC, dpryan79 approved these changes

2023-02-07 10:47 UTC, dpryan79 commented
@BiocondaBot please merge

2023-02-07 10:50 UTC, merged