Adding dysgu
bioconda/bioconda-recipes pull request #39627
Opened 2023-02-27 10:03 UTC by kcleal

Build of dysgu 1.3.14

2023-03-05 18:44 UTC, kcleal commented
@BiocondaBot please add label

2023-03-06 16:00 UTC, daler requested changes

2023-03-06 16:18 UTC, kcleal commented on recipes/dysgu/meta.yaml
> +    - 'pip install cython; dysgu --help'
I know its a bit unusual, but cython is required for the runtime. For some read cython is not installed in the test environment. Ive tried several options to try and get it to install such as having a requirements subsection within the test section, but nothing seems to make it install. If I put cython in the run section of requirements, then the lint fails!

2023-03-06 16:20 UTC, kcleal commented on recipes/dysgu/meta.yaml
> +  host:
For some reason the build fails without all of them in the host section. Perhaps something to do with cython needing to know they exists during compilation?

2023-03-06 16:22 UTC, kcleal commented on recipes/dysgu/meta.yaml
> +  host:
I can try this again, to see if they can be ommited

2023-03-06 16:23 UTC, kcleal commented on recipes/dysgu/meta.yaml
> +    - 'pip install cython; dysgu --help'
Do you know how I can get cython to install in the test section?

2023-03-06 18:48 UTC, daler commented on recipes/dysgu/meta.yaml
> +    - 'pip install cython; dysgu --help'
i guess i'm not clear why cython is required at runtime, but if the test fails without it, then the installed package will also be broken. If it's really a runtime dependency for some reason, there is a [lint skip mechanism](https://bioconda.github.io/contributor/linting.html#skipping-persistently-on-a-per-recipe-basis).

2023-03-07 08:52 UTC, kcleal commented on recipes/dysgu/meta.yaml
> +    - 'pip install cython; dysgu --help'
Thanks, this worked!

2023-03-07 14:17 UTC, daler approved these changes

2023-03-07 14:17 UTC, daler commented
@BiocondaBot please merge

2023-03-07 14:19 UTC, merged