[WIP] Add simple-omero-client fiji plugin
bioconda/bioconda-recipes pull request #39958
Opened 2023-03-17 10:39 UTC by lldelisle

Add simple-omero-client fiji plugin

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2023-03-17 12:58 UTC, ppouchin requested changes

2023-03-17 12:58 UTC, ppouchin commented on recipes/fiji-simple_omero_client/meta.yaml
> +  summary: Fiji/ImageJ plugin to simplify API to put/get objects on an OMERO server.
It is actually not specific to ImageJ/Fiji (although this package is), and does not provide any plugin in fact. 
Would it make sense to rephrase it as such?
```yaml
summary: Java library to simplify API to put/get objects on an OMERO server from Fiji/ImageJ.
```

2023-03-17 14:52 UTC, ppouchin commented on recipes/fiji-simple_omero_client/build.sh
> +outdir=$PREFIX/share/plugins/
I'm under the impression that libraries should go in the `jars` folder, but I'm not 100% sure.

2023-03-17 14:58 UTC, lldelisle commented on recipes/fiji-simple_omero_client/build.sh
> +outdir=$PREFIX/share/plugins/
I think it is fine to do it like this.

2023-03-17 16:22 UTC, ppouchin commented
Sounds good to me, but I guess the build will only pass once the dependency is uploaded to the repo.

2023-03-21 10:25 UTC, lldelisle commented
@BiocondaBot please add label

2023-03-22 21:31 UTC, bgruening commented
@BiocondaBot please merge

2023-03-22 21:34 UTC, merged

2023-03-22 21:40 UTC, lldelisle commented
Thank you so much @bgruening