add current_events_magnifier recipe
bioconda/bioconda-recipes pull request #41515
Opened 2023-06-15 10:58 UTC by JeremyQuo

Describe your pull request here
Add the current_events_magnifier to showcase ONT data
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2023-06-15 12:02 UTC, JeremyQuo commented
@bioconda-bot please add label

2023-07-01 08:13 UTC, bgruening requested changes
Thanks, a few comments inline.

2023-07-01 08:13 UTC, bgruening commented on recipes/current_events_magnifier/meta.yaml
> +  license_file:
This here is missing and please add the doc_url or clean up the recipe a bit. Thanks.

2023-07-01 08:13 UTC, bgruening commented on recipes/current_events_magnifier/meta.yaml
> +    - h5py ==3.8.0
you can remove everything but pip and python from the host requiremen

2023-07-01 08:13 UTC, bgruening commented on recipes/current_events_magnifier/meta.yaml
> +  noarch: generic
this looks like a noarch: python recipe

2023-07-01 08:13 UTC, bgruening commented on recipes/current_events_magnifier/meta.yaml
> +    - your-github-id-here
this is also not correct :)

2023-08-26 14:33 UTC, dpryan79 commented
@BiocondaBot please fetch artifacts

2023-08-26 15:27 UTC, dpryan79 commented
It seems the package name has changed. I can't easily rename the directory to match, so you'll need to do that.

2024-12-18 02:25 UTC, closed without merging