Add recipe for umi-transfer
bioconda/bioconda-recipes pull request #42034
Opened 2023-07-18 18:14 UTC by MatthiasZepper

This PR adds a recipe for [`umi-transfer`](https://github.com/SciLifeLab/umi-transfer), a tool for transferring Unique Molecular Identifiers (UMIs) from a separate FastQ file into the header of reads, while ensuring by ID comparison that only correct UMIs are integrated. This functionality was previously contained in [barcodex-rs](https://github.com/oicr-gsi/barcodex-rs), which is unfortunately no longer maintained and thus fails to build on Bioconda. 

The new tool is developed by scientists at the [Swedish National Genomics Infrastructure](https://ngisweden.scilifelab.se/) and published through the [SciLifeLab organisation](https://github.com/SciLifeLab/umi-transfer).

PS: Currently, this PR still points to a fork of said tool, where a test release of the latest version (the one to be added to Bioconda) has already been made. It will be changed if the CI succeeds for final review.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2023-07-26 01:28 UTC, bgruening commented
Is this still in Draft?

2023-07-27 05:35 UTC, MatthiasZepper commented
> Is this still in Draft?

Yes. Thank you very much for double-checking, though! I will make use of the bot when ready! 

The reason for it is, that it points to my personal fork of the software. But I[ can not make a release on the official repo without approval by a second person within the organization](https://github.com/SciLifeLab/umi-transfer/pull/10), and at the moment literally everyone is on holidays. I just wanted to make sure that tests pass, so I can tick off "Adding to Bioconda" on my ToDo list more or less.

2023-08-16 16:04 UTC, MatthiasZepper commented
@BiocondaBot please fetch artifacts

2023-08-16 16:54 UTC, MatthiasZepper commented
@BiocondaBot please fetch artifacts

2023-08-17 10:02 UTC, MatthiasZepper commented
@BiocondaBot please update
@BiocondaBot please add label

2023-08-17 10:20 UTC, MatthiasZepper commented
@BiocondaBot please add label

2023-08-21 00:07 UTC, mencian requested changes
Please add the license_file packaged with source, otherwise looks good to me!

2023-08-21 00:07 UTC, mencian commented on recipes/umi-transfer/meta.yaml
> +  license_family: MIT
```suggestion
  license_family: MIT
  license_file: LICENSE
```

2023-08-21 16:04 UTC, mencian approved these changes

2023-08-21 16:04 UTC, merged