Add hictkpy
bioconda/bioconda-recipes pull request #42362
Opened 2023-08-07 09:01 UTC by robomics

Add recipe for [paulsengroup/hictkpy](https://github.com/paulsengroup/hictkpy)

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2023-08-07 20:37 UTC, robomics commented
@BiocondaBot please fetch artifacts

2023-08-09 10:13 UTC, robomics commented
I am not sure where does `import hictkpy.hictkpy` come from:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/conda-bld/hictkpy_1691574443981/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/hictkpy/__init__.py", line 1, in <module>
    from .hictkpy import File, is_cooler, is_hic_file, __version__
ModuleNotFoundError: No module named 'hictkpy.hictkpy'
Tests failed for hictkpy-0.0.1-py310h8dd5466_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
WARNING:conda_build.build:Tests failed for hictkpy-0.0.1-py310h8dd5466_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
TESTS FAILED: hictkpy-0.0.1-py310h8dd5466_0.tar.bz2
```

2023-08-09 12:38 UTC, robomics commented
I think the issue is due to python version mismatch.
Libs inside the wheel are named like `hictkpy.cpython-311-x86_64-linux-gnu.so`, while the Python version installed by conda in CI (and also on a clean environment on my machine) is 3.10.

How does one build one conda package for each python version supported by a  library (Python 3.6 and newer in this case)?

2023-08-19 07:06 UTC, mencian requested changes
A few comments inline to have separate builds for each Python versions >=3.6

2023-08-19 07:06 UTC, mencian commented on recipes/hictkpy/meta.yaml
> +  number: 0
```suggestion
  number: 0
  skip: True  # [py < 36]
```

2023-08-19 07:06 UTC, mencian commented on recipes/hictkpy/meta.yaml
> +    - python >=3.6
```suggestion
    - python
```

2023-08-19 07:06 UTC, mencian commented on recipes/hictkpy/meta.yaml
> +    - python >=3.6
```suggestion
    - python
```

2023-08-19 12:45 UTC, robomics commented
@BiocondaBot please fetch artifacts

2023-08-19 15:14 UTC, robomics commented
@BiocondaBot please add label

@mencian many thanks for your comments!

2023-08-19 18:55 UTC, mencian approved these changes

2023-08-19 18:56 UTC, merged