Add Go-Figure! recipe
bioconda/bioconda-recipes pull request #42420
Opened 2023-08-10 08:52 UTC by hdetering

Please add Go-Figure! build files to bioconda-recipes.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2023-09-14 07:37 UTC, hdetering commented
Dear Bioconda team, is there anything I can do to help get this PR accepted?

2023-09-17 15:19 UTC, mencian requested changes
A comment in-line regarding SPDX identifiers, otherwise looks good to me!

2023-09-23 02:42 UTC, mencian commented on recipes/go-figure/meta.yaml
> +  license: GNU General Public License v3.0
```suggestion
  license: GPL-3.0-or-later
```

2023-09-23 03:01 UTC, mencian commented on recipes/go-figure/meta.yaml
> +  number: 0
```suggestion
  number: 0
  run_exports:
    - {{ pin_subpackage('go-figure', max_pin="x") }}
```

2023-09-23 03:25 UTC, mencian approved these changes

2023-09-23 03:25 UTC, merged