Add xengsort
bioconda/bioconda-recipes pull request #42536
Opened 2023-08-17 14:50 UTC by JZentgraf

Adding xengsort to bioconda.
Added a recipe using the pypi package and adapting the meta.yaml.

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2023-08-18 11:16 UTC, JZentgraf commented
@BiocondaBot please add label

2023-08-19 06:54 UTC, mencian requested changes
A couple of comments in-line, thanks.

2023-08-19 06:54 UTC, mencian commented on recipes/xengsort/meta.yaml
> +  noarch: generic
```suggestion
  noarch: python
```

2023-08-19 06:54 UTC, mencian commented on recipes/xengsort/meta.yaml
> +  license: MIT
```suggestion
  license: MIT
  license_file: LICENSE
```

2023-08-19 13:36 UTC, JZentgraf commented
Thanks for the comments!
I accepted both.

2023-08-19 18:55 UTC, mencian approved these changes

2023-08-19 18:55 UTC, merged