Add TE-Aid
bioconda/bioconda-recipes pull request #44954
Opened 2023-12-22 12:55 UTC by bricoletc

This PR adds [TE-Aid](https://github.com/clemgoub/TE-Aid), an '*Annotation helper tool for the manual curation of transposable element consensus sequences*' 

Linked issue: https://github.com/clemgoub/TE-Aid/issues/8
Missing from recipe: Licence file; release + version; sha256 of that release; link to original `source` and not my fork

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2025-03-03 20:54 UTC, Adamtaranto commented on recipes/te-aid/meta.yaml
> +
From https://github.com/clemgoub/TE-Aid/blob/main/TE_AID.yml

  - r-rcpp >=1.0.12
  - bioconductor-biostrings >=2.70.1
  
  Not sure if there is a diff between r and r-base from conda-forge

2025-03-04 04:09 UTC, Adamtaranto requested changes
Ask Clem to fix the tag name then recalc sha256

2025-03-04 04:09 UTC, Adamtaranto commented on recipes/te-aid/meta.yaml
> +{% set version = "0.1.0" %}
Tag is [v.1.0.0](https://github.com/clemgoub/TE-Aid/tree/v.1.0.0)

I guess try setting it as "1.0.0"

2025-03-04 04:09 UTC, Adamtaranto commented on recipes/te-aid/meta.yaml
> +  url: https://github.com/bricoletc/TE-Aid/archive/refs/tags/v{{ version }}.tar.gz
Ok that extra "." after the "v" is going to be annoying

2025-03-05 06:57 UTC, Adamtaranto commented on recipes/te-aid/meta.yaml
> +{% set sha256 = "2150a8bb7a16ceba29f824063dd7866da9e827e952b1dbf01fb61f0c89b18904" %}
Pending release with corrected version, will check if sha has changed.

2025-03-05 20:51 UTC, Adamtaranto approved these changes
Release number and SHA have been corrected. Tests passing.

2025-03-05 20:52 UTC, Adamtaranto commented
@BiocondaBot please add label

2025-03-05 21:02 UTC, Adamtaranto commented
@martin-g can you please review and merge?

Biocondabot isn't adding a label. Probably because I added a review to resolve requests from an earlier review.

2025-03-07 07:42 UTC, martin-g approved these changes

2025-03-07 07:42 UTC, merged