gridss: add linux-aarch64 build
bioconda/bioconda-recipes pull request #47228
Opened 2024-04-15 08:36 UTC by martin-g

Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2024-05-01 11:41 UTC, martin-g commented
The Linux ARM6 build depends on:
```
 The reported errors are:[0m
08:42:29 [32mBIOCONDA INFO[0m (OUT) - Encountered problems while solving:[0m
08:42:29 [32mBIOCONDA INFO[0m (OUT) -   - nothing provides requested bwa >=0.7[0m
08:42:29 [32mBIOCONDA INFO[0m (OUT) -   - nothing provides requested kraken2 >=2.1[0m
08:42:29 [32mBIOCONDA INFO[0m (OUT) -   - nothing provides rmblast needed by repeatmasker-4.1.1-pl5262hdfd78af_2[0m
08:42:29 [32mBIOCONDA INFO[0m (OUT) -   - nothing provides bioconductor-biostrings >=2.62.0,<2.63.0 needed by bioconductor-structuralvariantannotation-1.10.0-r41hdfd78af_0[0m
```

2025-02-23 23:45 UTC, brainstorm commented
@martin-g Let me know if you need some assistance with this one, it's on our critical path to ship OncoAnalyser w/ ARM64 support ;)

/cc @scwatts

2025-02-24 00:01 UTC, brainstorm requested changes
LGTM overall...considering all the deps are successfully packaged for `linux-aarch64` (kudos @martin-g). Only nits are a couple of lints on meta.yml, easy to solve from the looks of it.

I will definitely test this on runtime soon whenever it gets merged, so we can iterate fast if there's any issues post-merging.

2025-02-24 08:24 UTC, martin-g commented
Thanks for the ping, @brainstorm !
I've updated the PR! 
Let's see how it goes!

2025-02-24 08:50 UTC, martin-g commented
@BiocondaBot please fetch artifacts

2025-02-24 08:59 UTC, martin-g commented
```
mgrigorov in 🌐 euler-arm-22 in /tmp/gridss took 32s 
❯ tar xvf gridss-2.13.2-h0b41a95_5.tar.bz2 
info/run_exports.json
info/hash_input.json
info/recipe/0002-set-gridssargs-for-virusbreakend-annotation.patch
info/recipe/0001-fix-samtools-version-check.patch
info/test/run_test.sh
info/index.json
info/recipe/gridss_r_script
info/recipe/gridss_shell_with_jar_entrypoint
info/files
info/recipe/gridss_java_entrypoint
info/recipe/meta.yaml.template
info/recipe/meta.yaml
info/recipe/build.sh
info/recipe/conda_build_config.yaml
info/about.json
info/paths.json
info/git
share/gridss-2.13.2-5/gridss_r_script
share/gridss-2.13.2-5/gridss_shell_with_jar_entrypoint
share/gridss-2.13.2-5/gridss_java_entrypoint
share/gridss-2.13.2-5/gridss_annotate_vcf_kraken2
share/gridss-2.13.2-5/gridss_annotate_vcf_repeatmasker
share/gridss-2.13.2-5/gridss_extract_overlapping_fragments
share/gridss-2.13.2-5/gridss_somatic_filter
share/gridss-2.13.2-5/virusbreakend
share/gridss-2.13.2-5/gridss
share/gridss-2.13.2-5/gridss.jar
bin/gridss_somatic_filter
bin/IdentifyViralTaxa
bin/CollectStructuralVariantReadMetrics
bin/AnnotateInexactHomology
bin/CollectGridssMetrics
bin/SoftClipsToSplitReads
bin/AssembleBreakends
bin/InsertedSequencesToFasta
bin/PreprocessForBreakendAssembly
bin/ReportThresholdCoverage
bin/VirusBreakendFilter
bin/CollectFragmentGCMetrics
bin/AllocateEvidence
bin/CollectGridssMetricsAndExtractSVReads
bin/SubsetToTaxonomy
bin/GeneratePonBedpe
bin/AnnotateInsertedSequence
bin/CollectIdsvMetrics
bin/CollectTagMetrics
bin/SanityCheckEvidence
bin/ExtractBestViralReference
bin/ExtractSVReads
bin/IdentifyVariants
bin/AnnotateReferenceCoverage
bin/CallVariants
bin/AnnotateInexactHomologyBedpe
bin/ComputeSamTags
bin/PrepareReference
bin/AnnotateVariantsRepeatMasker
bin/AnnotateVariantsKraken
bin/ExtractFragmentsToFastq
bin/CollectCigarMetrics
bin/AnnotateVariants
bin/CollectMapqMetrics
bin/virusbreakend
bin/gridss_annotate_vcf_repeatmasker
bin/gridss_annotate_vcf_kraken2
bin/gridss_extract_overlapping_fragments
bin/gridss
bin/virusbreakend-build
bin/gridsstools
share/gridss-2.13.2-5/gridss.config.R
share/gridss-2.13.2-5/libgridss.R

mgrigorov in 🌐 euler-arm-22 in /tmp/gridss took 3s 
❯ file ./bin/*
./bin/AllocateEvidence:                      symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AnnotateInexactHomology:               symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AnnotateInexactHomologyBedpe:          symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AnnotateInsertedSequence:              symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AnnotateReferenceCoverage:             symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AnnotateVariants:                      symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AnnotateVariantsKraken:                symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AnnotateVariantsRepeatMasker:          symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/AssembleBreakends:                     symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CallVariants:                          symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectCigarMetrics:                   symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectFragmentGCMetrics:              symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectGridssMetrics:                  symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectGridssMetricsAndExtractSVReads: symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectIdsvMetrics:                    symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectMapqMetrics:                    symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectStructuralVariantReadMetrics:   symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/CollectTagMetrics:                     symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/ComputeSamTags:                        symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/ExtractBestViralReference:             symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/ExtractFragmentsToFastq:               symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/ExtractSVReads:                        symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/GeneratePonBedpe:                      symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/gridss:                                symbolic link to ../share/gridss-2.13.2-5/gridss_shell_with_jar_entrypoint
./bin/gridss_annotate_vcf_kraken2:           symbolic link to ../share/gridss-2.13.2-5/gridss_shell_with_jar_entrypoint
./bin/gridss_annotate_vcf_repeatmasker:      symbolic link to ../share/gridss-2.13.2-5/gridss_shell_with_jar_entrypoint
./bin/gridss_extract_overlapping_fragments:  symbolic link to ../share/gridss-2.13.2-5/gridss_shell_with_jar_entrypoint
./bin/gridss_somatic_filter:                 symbolic link to ../share/gridss-2.13.2-5/gridss_r_script
./bin/gridsstools:                           ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
./bin/IdentifyVariants:                      symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/IdentifyViralTaxa:                     symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/InsertedSequencesToFasta:              symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/PrepareReference:                      symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/PreprocessForBreakendAssembly:         symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/ReportThresholdCoverage:               symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/SanityCheckEvidence:                   symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/SoftClipsToSplitReads:                 symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/SubsetToTaxonomy:                      symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint
./bin/virusbreakend:                         symbolic link to ../share/gridss-2.13.2-5/gridss_shell_with_jar_entrypoint
./bin/virusbreakend-build:                   Bourne-Again shell script, ASCII text executable
./bin/VirusBreakendFilter:                   symbolic link to ../share/gridss-2.13.2-5/gridss_java_entrypoint

mgrigorov in 🌐 euler-arm-22 in /tmp/gridss via 🅒 test123 
❯ ./bin/gridsstools                                                                                                                                                                                        (test123) 

Program: gridsstools (C port of some GRIDSS tools)
Version: 1.0

Usage:   gridsstools <command> [options]

Command: extractFragmentsToFastq        Extracts a subset of reads by name to fastq
         extractFragmentsToBam          Extracts a subset of reads by name
         unmappedSequencesToFastq       Extracts unmapped reads and bases to fastq

```

LGTM!

2025-02-24 08:59 UTC, martin-g commented
@BiocondaBot please add label

2025-02-24 18:17 UTC, brainstorm approved these changes

2025-02-24 18:18 UTC, merged

2025-02-24 18:22 UTC, brainstorm commented
Thanks heaps for this! I'll report back :)