Add new recipe for Souporcell
bioconda/bioconda-recipes pull request #47935
Opened 2024-05-17 18:12 UTC by wxicu

Describe your pull request here
Add new recipe for Souporcell
----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

### General instructions

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

### Instructions for avoiding API, ABI, and CLI breakage issues
Conda is able to record and lock (a.k.a. pin) dependency versions used at build time of other recipes.
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:

```yaml
build:
  run_exports:
    - ...

```

with `...` being one of:

| Case                             | run_exports statement                                               |
| -------------------------------- | ------------------------------------------------------------------- |
| semantic versioning              | `{{ pin_subpackage("myrecipe", max_pin="x") }}`     |
| semantic versioning (0.x.x)      | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}`   |
| known breakage in minor versions | `{{ pin_subpackage("myrecipe", max_pin="x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| known breakage in patch versions | `{{ pin_subpackage("myrecipe", max_pin="x.x.x") }}` (in such a case, please add a note that shortly mentions your evidence for that) |
| calendar versioning              | `{{ pin_subpackage("myrecipe", max_pin=None) }}`    |

while replacing `"myrecipe"` with either `name` if a `name|lower` variable is defined in your recipe or with the lowercase name of the package in quotes.

### Bot commands for PR management

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge instead.

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

2024-09-09 13:53 UTC, aliciaaevans commented
@wxicu There have been several of these PRs recently that have this disconnect issue. I'm going to try building them on our bulk branch that uses GitHub Actions for CI. Can you please undo any unwanted changes that you made to experiment on this branch and let me know if/when the recipe is ready?

2024-09-09 18:50 UTC, wxicu commented
> @wxicu There have been several of these PRs recently that have this disconnect issue. I'm going to try building them on our bulk branch that uses GitHub Actions for CI. Can you please undo any unwanted changes that you made to experiment on this branch and let me know if/when the recipe is ready?

Hey thank you for taking care of this PR. I just updated the branch. The recipe is ready

2024-09-10 19:41 UTC, aliciaaevans commented
@wxicu `vatrix` is not available in `bioconda` or `conda-forge` channels.

2024-09-10 19:47 UTC, aliciaaevans commented
> @wxicu `vatrix` is not available in `bioconda` or `conda-forge` channels.

I just realized this probably should be `vartrix`. I'll try that.

2024-09-10 20:55 UTC, aliciaaevans commented
Correcting the typo in `vartrix` allowed it to solve, but now getting `make: *** No targets specified and no makefile found. Stop.`
This file has the last few lines of the log: https://github.com/bioconda/bioconda-recipes/commit/ae06127efc8836b9bed864ab6bc7fca1b5962f6c

2024-09-11 21:39 UTC, wxicu commented
I don't know what is happening here. Could you please tell me how can I get the log file? I test the build with`bioconda-utils build --packages souporcell --mulled-test --loglevel debug` and got 
```
23:17:45 BIOCONDA INFO (OUT) +GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g++
.23:17:52 BIOCONDA ERROR COMMAND FAILED (exited with 1): /home/icb/xichen.wu/miniconda3/envs/bioconda/bin/conda-build --override-channels --no-anaconda-uplo
ad -c conda-forge -c bioconda -e /home/icb/xichen.wu/miniconda3/envs/bioconda/conda_build_config.yaml -e /home/icb/xichen.wu/miniconda3/envs/bioconda/lib/py
thon3.10/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/souporcell/meta.yaml

23:17:52 BIOCONDA ERROR BUILD FAILED recipes/souporcell
23:17:52 BIOCONDA INFO (COMMAND) conda build purge
23:18:16 BIOCONDA INFO Command closed STDOUT/STDERR but is still running
23:18:16 BIOCONDA INFO Waiting 30 seconds (1/5)
23:18:16 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
23:18:16 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/souporcell
```
without any further details.

2024-09-12 13:41 UTC, aliciaaevans commented
If you click the Checks tab and then Azure piplelines on the sidebar, there's a link to Azure to get to the logs. Here's a direct link: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=68830&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=334

For local, you can try running without the mulled test option.

2025-01-30 13:00 UTC, mfansler requested changes
I'd also like to see this added. Here are some changes to consider.

@wxicu I would be willing to take this over if you lack time.

2025-01-31 10:15 UTC, mfansler commented
Fails compiling `souporcell` with [complaint about VCFReader](https://github.com/bioconda/bioconda-recipes/actions/runs/13069177826/job/36466998862?pr=47935#step:7:941):

```rust
error[E0277]: `vcf::VCFReader<Box<dyn BufRead>>` is not an iterator
   --> src/main.rs:320:19
    |
320 |     for record in vcf_reader {
    |                   ^^^^^^^^^^ `vcf::VCFReader<Box<dyn BufRead>>` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `vcf::VCFReader<Box<dyn BufRead>>`
    = note: required for `vcf::VCFReader<Box<dyn BufRead>>` to implement `IntoIterator`
```

2025-02-03 16:15 UTC, mfansler requested changes

2025-02-03 16:15 UTC, mfansler commented on recipes/souporcell/build.sh
> +cargo install --verbose --root "${PREFIX}/bin/troublet/target/release/" --path troublet
I think the path is still wrong in the end. Files ultimately end up at `${PREFIX}/bin/souporcell/target/release/bin/`. Might be better to build in place then `cp` to where it needs to go.

2025-02-03 16:15 UTC, mfansler commented on recipes/souporcell/meta.yaml
> +    - souporcell_pipeline.py -h
I think we need something a little more substantial here. E.g., I don't think that this checks that the binaries are in the expected locations.

2025-02-17 09:37 UTC, mfansler commented on recipes/souporcell/meta.yaml
> +    - souporcell_pipeline.py -h
The only example data I see is resource intensive, so will have to manually test artifacts. For now, I included all binaries and scripts that are executable.

2025-02-17 09:38 UTC, mfansler commented on recipes/souporcell/build.sh
> +cargo install --verbose --root "${PREFIX}/bin/troublet/target/release/" --path troublet
Using `cargo build --release` ends up with a triplet, but we can use `install` after that (I think).

2025-02-17 12:47 UTC, martin-g commented on recipes/souporcell/build.sh
> +cp -f *py $PREFIX/bin
```suggestion
cp -f *.py $PREFIX/bin
```

2025-02-17 12:47 UTC, martin-g commented on recipes/souporcell/meta.yaml
> +    - {{ pin_subpackage('souporcell', max_pin="x.x") }}
```suggestion
    - {{ pin_subpackage('souporcell', max_pin="x") }}
```
?

2025-02-17 12:47 UTC, martin-g commented on recipes/souporcell/meta.yaml
> +extra:
```suggestion
extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
```
?

2025-02-17 13:35 UTC, mfansler commented on recipes/souporcell/meta.yaml
> +extra:
This depends on `vartrix`, which we do not compile. Instead we currently do binary redistribution of the 10X releases. Someone would first need to work on that.

Also, I had issue with even the `osx-64` build and compiling the (Py)Stan model. For now this will only have `linux-64`.

2025-02-17 13:39 UTC, mfansler commented
@BiocondaBot please fetch artifacts

2025-02-17 17:18 UTC, mfansler approved these changes

2025-02-17 17:19 UTC, mfansler commented
@martin-g thanks for the review. I locally tested the artifact and confirmed it works. I'll leave this to you for (re-)review and merge.

2025-02-17 17:23 UTC, mfansler commented on recipes/souporcell/meta.yaml
> +    - souporcell_pipeline.py -h
I have tested the artifact on [the demo data](https://github.com/wheaton5/souporcell?tab=readme-ov-file#practicetesting-data-set-demuxlet-paper-data). All steps ran without issue, though maybe worth noting that I used the `--skip_remap SKIP_REMAP` option (with common variants), so it didn't test running `minimap2`.

But the scripts work and both binaries (souporcell, troublet) executed without issue.

2025-02-17 18:16 UTC, martin-g approved these changes

2025-02-17 18:16 UTC, merged