add chain2paf
bioconda/bioconda-recipes pull request #52801
Opened 2024-12-14 15:27 UTC by AndreaGuarracino

Add `chain2paf` to convert sequence alignment from CHAIN to PAF format.

2024-12-17 11:35 UTC, mbhall88 requested changes
Please see the [guidelines for Rust recipes](https://bioconda.github.io/contributor/guidelines.html#rust) for licensing and additional cargo flags

2024-12-17 16:06 UTC, AndreaGuarracino commented
Hi @mbhall88, sorry for the dumbness, what's missing about the LICENSE or flags? Thanks to @martin-g, also ARM's tests pass now.

2024-12-17 19:33 UTC, mbhall88 commented
No need to apologise. Sorry for my abrupt response. That link above has an example of a best practice recipe. In particular, bundling licenses of dependencies and adding no track option. Sorry, not at my computer at the moment to add code suggestions

2024-12-17 23:17 UTC, mbhall88 commented on recipes/chain2paf/meta.yaml
> +    - {{ compiler('rust') }}
```suggestion
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
```

2024-12-17 23:21 UTC, mbhall88 commented on recipes/chain2paf/meta.yaml
> +  license_file: LICENSE
```suggestion
  license_file: 
    - LICENSE
    - THIRDPARTY.yml
```

2024-12-18 00:12 UTC, mbhall88 approved these changes

2024-12-18 00:12 UTC, merged